from collections import deque
q = deque(maxlen=3)
q.append('a')
q.append('b')
q.append('c')
q.appendleft('c')
q.extendleft(['d', 'e'])
print("Initial queue")
print(q)
print("\nElements dequeued from the queue")
print(q.popleft())
print(q.popleft())
print(q.popleft())

print("\nQueue after removing elements")
print(q)
